export enum PhoneNumberType {
	UAN = "UAN",
	VOIP = "VOIP",
	PAGER = "PAGER",
	MOBILE = "MOBILE",
	UNKNOWN = "UNKNOWN",
	VOICEMAIL = "VOICEMAIL",
	TOLL_FREE = "TOLL_FREE",
	FIXED_LINE = "FIXED_LINE",
	SHARED_COST = "SHARED_COST",
	PREMIUM_RATE = "PREMIUM_RATE",
	PERSONAL_NUMBER = "PERSONAL_NUMBER",
	FIXED_LINE_OR_MOBILE = "FIXED_LINE_OR_MOBILE",
}
