name: Test Angular Versions

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-angular-versions:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        angular_version: ["12", "13", "14", "15", "16", "17", "18", "19"]

    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Angular version ${{ matrix.angular_version }}
        run: |
          # Angular runtime dependencies
          npm install @angular/animations@${{ matrix.angular_version }} --save --force
          npm install @angular/common@${{ matrix.angular_version }} --save --force
          npm install @angular/compiler@${{ matrix.angular_version }} --save --force
          npm install @angular/core@${{ matrix.angular_version }} --save --force
          npm install @angular/forms@${{ matrix.angular_version }} --save --force
          npm install @angular/platform-browser@${{ matrix.angular_version }} --save --force
          npm install @angular/platform-browser-dynamic@${{ matrix.angular_version }} --save --force
          npm install @angular/router@${{ matrix.angular_version }} --save --force

          # Angular dev dependencies
	  npm install @angular-devkit/build-angular@${{ matrix.angular_version }} --save-dev --force
	  npm install @angular/cli@${{ matrix.angular_version }} --save-dev --force
	  npm install @angular/compiler-cli@${{ matrix.angular_version }} --save-dev --force
	  npm install @angular/language-service@${{ matrix.angular_version }} --save-dev --force

          npm install --force

      - name: Run Angular build 🔧
        run: npm run build

